# Set a default custom join message. {NAME} will be replaced with player's name. Leave empty for default Minecraft message.
custom_join_message: ""

# Set a default leave join message, {NAME} will be replaced with player's name. Leave empty for default Minecraft message.
custom_leave_message: ""

# Custom messages are stored here
saved_messages:
  join:
  leave:
