name: CustomJoinMessages
version: '${project.version}'
main: com.milan25.customjoinmessages.CustomJoinMessages
api-version: '1.21'
authors: [ milan_25 ]
description: Custom join and leave messages
depend: [PlaceholderAPI]
